const reducer = {
  LOADING: 'LOADING',
  ISLOGIN: 'ISLOGIN',
  ISFIRSTLAUNCH: 'ISFIRSTLAUNCH',
  DISABLE: 'DISABLE',
  DATAUSER: 'DATAUSER',
  PHONENUMBER: 'PHONENUMBER',
};

const cartAction = {
  ADDCART: 'ADDCART',
  PLUSCART: 'PLUSCART',
  MINCART: 'MINCART',
};

export {reducer, cartAction};
